name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore packages
        run: dotnet restore ./ControlAsistencia/ControlAsistencia.sln

      - name: Begin SonarCloud Analysis
        run: dotnet sonarscanner begin /k:"API_BANK" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /o:"alvarocontreras13"

      - name: Build
        run: dotnet build ./ControlAsistencia/ControlAsistencia.sln --no-restore

      - name: Run Tests
        run: dotnet test ./ControlAsistencia/ControlAsistencia.sln --collect:"XPlat Code Coverage;Format=opencover"

      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
